# fly.toml app configuration file generated for zebra-backend on 2025-02-17T15:35:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zebra-backend'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/go']

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
